// Demonstração local: use somente dados e senhas fictícios.
const STORE='simpatia257.demo.v1';
const escapeHtml=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=value=>Number(value).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const seed=()=>({version:1,users:[{id:'admin',name:'Administração',email:'admin@simpatia.demo',password:'admin123',role:'admin'},{id:'cliente',name:'Marina Exemplo',email:'cliente@simpatia.demo',password:'cliente123',role:'cliente'}],requests:[],session:null});
let db=seed(),storageError='';
try{const raw=localStorage.getItem(STORE);if(raw){const parsed=JSON.parse(raw);if(parsed.version!==1||!Array.isArray(parsed.users)||!Array.isArray(parsed.requests))throw Error('Formato inválido');db=parsed;}else localStorage.setItem(STORE,JSON.stringify(db));}catch(error){storageError='Não foi possível ler ou salvar os dados locais. Habilite o armazenamento do navegador ou reinicie a demonstração.';}
const user=()=>db.users.find(u=>u.id===db.session);
const admin=()=>user()?.role==='admin';
const own=r=>r&&(admin()||r.userId===user()?.id);
const active=r=>!['Cancelada','Recusada'].includes(r.status);
const overlaps=(a,b)=>a.id!==b.id&&active(a)&&active(b)&&a.room===b.room&&a.date===b.date&&a.start<b.end&&b.start<a.end;
const conflicts=r=>db.requests.filter(other=>overlaps(r,other));
const uid=()=>globalThis.crypto?.randomUUID?.()||Date.now().toString(36)+Math.random().toString(36).slice(2);
function commit(change){const before=JSON.stringify(db);try{if(storageError)throw Error(storageError);change();localStorage.setItem(STORE,JSON.stringify(db));}catch(e){db=JSON.parse(before);throw e;}}
function go(path){if(location.hash==='#'+path)render();else location.hash=path;}
function notify(message){document.getElementById('demo').querySelector('p').textContent=message;document.getElementById('demo').showModal();}
const control=(label,name,type='text',value='',extra='')=>`<div class="field"><label>${escapeHtml(label)}<input name="${name}" type="${type}" value="${escapeHtml(value)}" ${extra}></label></div>`;
const pick=(label,name,options,value='')=>`<div class="field"><label>${escapeHtml(label)}<select name="${name}" required>${options.map(([v,l])=>`<option value="${escapeHtml(v)}" ${v===value?'selected':''}>${escapeHtml(l)}</option>`).join('')}</select></label></div>`;
const area=(label,name,value='')=>`<div class="field"><label>${label}<textarea name="${name}" maxlength="2000">${escapeHtml(value)}</textarea></label></div>`;
const localForm=(kind,body,label,id='')=>`<form class="card form" data-form="${kind}" data-id="${id}">${body}<p class="form-error" role="alert"></p><button class="btn" type="submit">${label}</button><p class="help">Teste local. Use dados fictícios. Nenhum pagamento ou envio real.</p></form>`;
const act=(label,kind,id='')=>`<button type="button" class="btn light" data-action="${kind}" data-id="${id}">${label}</button>`;
const empty=()=>'<div class="card"><p>Nenhum pedido nesta lista.</p></div>';
const visible=()=>db.requests.filter(own);
const dateText=value=>value.split('-').reverse().join('/');
const summary=r=>`<p><strong>${escapeHtml(r.title)}</strong><br>Sala ${r.room} · ${dateText(r.date)} · ${r.start} às ${r.end}</p>${tag(escapeHtml(r.status))}`;
const table=list=>list.length?`<div class="card table-wrap"><table><thead><tr><th>Atividade</th><th>Sala / Data</th><th>Status</th><th></th></tr></thead><tbody>${list.map(r=>`<tr><td>${escapeHtml(r.title)}<br><small>${escapeHtml(db.users.find(u=>u.id===r.userId)?.name)}</small></td><td>${r.room} · ${dateText(r.date)}<br>${r.start}–${r.end}</td><td>${tag(escapeHtml(r.status))}</td><td>${btn('Ver pedido',(admin()?'avaliar':'reserva')+'?id='+r.id,true)}</td></tr>`).join('')}</tbody></table></div>`:empty();
const schedule=(r={})=>`<div class="grid">${pick('Sala','room',[['A','Sala A'],['D','Sala D']],r.room||'A')}${control('Data','date','date',r.date||'','required')}${control('Início','start','time',r.start||'','required')}${control('Término','end','time',r.end||'','required')}</div>`;
const statusCards=list=>`<div class="stats">${[['Em análise',list.filter(r=>['Em análise','Em espera'].includes(r.status)).length],['Orçamentos',list.filter(r=>r.status==='Orçamento enviado').length],['Confirmadas',list.filter(r=>r.status==='Confirmada').length]].map(([label,n])=>`<div class="card stat"><strong>${n}</strong><span>${label}</span></div>`).join('')}</div>`;
const selected=()=>{const r=db.requests.find(r=>r.id===new URLSearchParams(location.hash.split('?')[1]).get('id'));return own(r)?r:null;};
const withRequest=fn=>{const r=selected();return r?fn(r):head('Pedido indisponível','Escolha um pedido da sua lista.')+btn('Voltar',admin()?'pedidos':'reservas');};
const credentials='<div class="callout"><strong>Contas de teste</strong><br>Cliente: cliente@simpatia.demo · senha: cliente123<br>Administrador: admin@simpatia.demo · senha: admin123<br>Dados ficam apenas neste navegador. Não use senhas reais.</div>';
pages.login=()=>head('Entrar na demonstração','Faça um pedido como cliente e depois entre como administrador para avaliá-lo.')+credentials+localForm('login',control('E-mail','email','email','','required autocomplete="username"')+control('Senha fictícia','password','password','','required autocomplete="current-password"'),'Entrar')+`<div class="actions">${btn('Criar cadastro','cadastro',true)}</div>`;
pages.cadastro=()=>head('Criar cadastro de teste','O cadastro cria um cliente neste navegador.')+localForm('register',control('Nome','name','text','','required maxlength="100"')+control('E-mail fictício','email','email','','required')+control('Senha fictícia (mínimo 6 caracteres)','password','password','','required minlength="6"')+control('Confirmar senha','confirm','password','','required minlength="6"'),'Cadastrar');
pages.perfil=()=>head('Meu perfil','Altere seus dados de demonstração.')+localForm('profile',control('Nome','name','text',user().name,'required maxlength="100"')+control('E-mail','email','email',user().email,'required')+control('Telefone fictício','phone','tel',user().phone||'')+control('Organização','organization','text',user().organization||''),'Salvar perfil');
pages.painel=()=>head('Olá, '+escapeHtml(user().name),'Acompanhe os pedidos salvos neste navegador.')+statusCards(visible())+`<div class="actions">${btn('Nova reserva','reservar')}</div><br>`+table(visible());
pages.gestao=()=>head('Gestão do espaço','Pedidos de todos os clientes deste navegador.')+statusCards(db.requests)+table(db.requests);
pages.reservas=()=>head('Minhas reservas','Histórico e solicitações locais.')+table(visible());
pages.pedidos=()=>head('Avaliar pedidos','Selecione um pedido para analisar disponibilidade e enviar orçamento.')+table(db.requests);
pages.reservar=()=>head('Reservar uma sala','O pedido será avaliado pelo administrador na demonstração.')+localForm('reserve',schedule({room:new URLSearchParams(location.hash.split('?')[1]).get('sala')==='D'?'D':'A'})+control('Atividade','title','text','','required maxlength="120"')+control('Participantes','participants','number','1','required min="1" max="1000" step="1"')+area('Detalhes','details')+'<p class="callout">Estimativa de teste: R$ 100 por hora. O orçamento final é definido pelo administrador.</p>','Solicitar reserva');
function detail(r){return summary(r)+`<p>${escapeHtml(r.details)}</p><p>Participantes: ${r.participants}</p>`+(r.message?`<div class="callout">${escapeHtml(r.message)}</div>`:'')+(r.quote?`<p>Orçamento: ${money(r.quote.total)} · Taxa: ${money(r.quote.fee)}</p>${btn('Consultar orçamento','orcamento?id='+r.id,true)}`:'');}
pages.reserva=()=>withRequest(r=>head('Seu pedido','Acompanhe a avaliação e as próximas etapas.')+`<div class="card">${detail(r)}<div class="actions">${active(r)?btn('Alterar ou cancelar','alteracoes?id='+r.id,true):''}</div></div>`);
pages.avaliar=()=>withRequest(r=>head('Avaliar pedido','Revise os dados e a disponibilidade.')+`<div class="card">${detail(r)}${conflicts(r).length?'<div class="callout">Há pedidos com horário sobreposto. Resolva a agenda antes de confirmar.</div>':''}<div class="actions">${active(r)&&r.status!=='Confirmada'?btn('Preparar orçamento','enviar-orcamento?id='+r.id):''}${active(r)?act('Colocar em espera','wait',r.id)+btn('Propor outro horário','reagendar?id='+r.id,true)+act('Cancelar pedido','cancel',r.id):''}${!r.quote&&active(r)?act('Recusar pedido','reject',r.id):''}</div></div>`);
pages.orcamentos=()=>head('Meus orçamentos','Propostas recebidas nesta demonstração.')+table(visible().filter(r=>r.quote));
pages.orcamento=()=>withRequest(r=>head('Orçamento','Proposta de teste, sem cobrança real.')+`<div class="card">${summary(r)}${r.quote?`<p>Total: <strong>${money(r.quote.total)}</strong><br>Taxa incluída: ${money(r.quote.fee)}<br>Saldo: ${money(r.quote.total-r.quote.fee)}</p><p>${escapeHtml(r.quote.notes)}</p><div class="actions">${active(r)?btn('Termo e taxa','termo?id='+r.id):''}</div>`:'<p>O orçamento ainda não foi enviado.</p>'}</div>`);
pages.termo=()=>withRequest(r=>head('Termo e taxa','Simulações de assinatura e pagamento, sem validade real.')+`<div class="card">${summary(r)}${r.quote&&active(r)?`<p>Termo: ${r.signed?'assinatura simulada registrada':'pendente'}<br>Taxa: ${r.paid?'pagamento simulado registrado':'pendente'}</p><div class="actions">${!r.signed?act('Simular assinatura','sign',r.id):''}${!r.paid?act('Simular pagamento de '+money(r.quote.fee),'pay',r.id):''}</div><p>Depois dessas etapas, o administrador poderá confirmar a reserva.</p>`:'<p>É necessário um orçamento ativo.</p>'}</div>`);
pages.confirmada=()=>withRequest(r=>head(r.status==='Confirmada'?'Reserva confirmada na demonstração':'Reserva ainda não confirmada','Nenhuma reserva real foi realizada.')+`<div class="card">${summary(r)}</div>`);
pages['enviar-orcamento']=()=>withRequest(r=>head('Enviar orçamento','A proposta ficará visível na conta do cliente.')+(active(r)&&r.status!=='Confirmada'?localForm('quote',summary(r)+control('Valor total (R$)','total','number',r.quote?.total||300,'required min="0.01" step="0.01"')+control('Taxa incluída no total (R$)','fee','number',r.quote?.fee??90,'required min="0" step="0.01"')+area('Condições','notes',r.quote?.notes||''),'Enviar orçamento',r.id):'<p>Este pedido não pode receber orçamento.</p>'));
pages.alteracoes=()=>withRequest(r=>head('Alterar ou cancelar','O administrador avaliará sua solicitação.')+(active(r)?localForm('change',summary(r)+pick('Solicitação','kind',[['change','Alterar data / horário / sala'],['cancel','Cancelar reserva']])+`<div data-change-schedule>${schedule(r)}</div>`+area('Motivo','reason'),'Enviar solicitação',r.id):'<p>Pedido encerrado.</p>'));
pages.reagendar=()=>withRequest(r=>head('Propor outro horário','O cliente poderá aceitar ou recusar a proposta.')+localForm('propose',schedule(r)+area('Mensagem','reason'),'Enviar proposta ao cliente',r.id));
pages.conflitos=()=>head('Conflitos de agenda','Pedidos ativos com sobreposição de sala, data e horário.')+table(db.requests.filter(r=>conflicts(r).length));
pages.confirmacoes=()=>head('Termos e confirmações','Confirme após assinatura e taxa simuladas.')+(db.requests.filter(r=>r.quote&&active(r)).map(r=>`<div class="card" style="margin-bottom:20px">${summary(r)}<p>Termo: ${r.signed?'assinado':'pendente'} · Taxa: ${r.paid?'paga':'pendente'}</p>${r.status==='Confirmada'?btn('Ver confirmação','confirmada?id='+r.id,true):r.signed&&r.paid?act('Confirmar reserva','confirm',r.id):act('Enviar lembrete local','remind',r.id)}</div>`).join('')||empty());
pages.solicitacoes=()=>head('Solicitações dos clientes','Aprove ou recuse alterações e cancelamentos.')+(db.requests.filter(r=>r.change).map(r=>`<div class="card" style="margin-bottom:20px">${summary(r)}<p>${r.change.kind==='cancel'?'Cancelamento':`Nova agenda: Sala ${r.change.room} · ${dateText(r.change.date)} · ${r.change.start}–${r.change.end}`}</p><p>${escapeHtml(r.change.reason)}</p><div class="actions">${act('Aprovar','approve-change',r.id)}${act('Recusar','deny-change',r.id)}</div></div>`).join('')||empty());
const originalDetail=pages.reserva;
pages.reserva=()=>originalDetail()+(selected()?.proposal?`<div class="card" style="margin-top:20px"><h2>Proposta de novo horário</h2><p>Sala ${selected().proposal.room} · ${dateText(selected().proposal.date)} · ${selected().proposal.start}–${selected().proposal.end}</p><p>${escapeHtml(selected().proposal.reason)}</p><div class="actions">${act('Aceitar horário','accept-proposal',selected().id)}${act('Recusar horário','deny-proposal',selected().id)}</div></div>`:'');
const publicPages=['inicio','salas','atividades','regras','login','cadastro'];
const adminPages=[...adminLinks.map(([id])=>id),'avaliar','reagendar'];
function render(){const requested=location.hash.slice(1).split('?')[0]||'inicio';let page=pages[requested]?requested:'inicio';if(!user()&&!publicPages.includes(page))page='login';if(user()&&adminPages.includes(page)&&!admin())page='painel';document.getElementById('admin-menu').hidden=!admin();document.getElementById('client-menu').hidden=!user()||admin();const links=(list)=>list.map(([id,label])=>`<a href="#${id}" ${id===page?'class="active" aria-current="page"':''}>${label}</a>`).join('');document.getElementById('client-nav').innerHTML=links(clientLinks);document.getElementById('admin-nav').innerHTML=links(adminLinks)+links([['perfil','Meu perfil']]);document.getElementById('account-panel').innerHTML=user()?`<p><strong>${escapeHtml(user().name)}</strong><br><small>${admin()?'Administrador':'Cliente'} · conta de teste</small></p>${act('Sair','logout')}`:btn('Entrar / Cadastrar','login',true);document.getElementById('header-account').textContent=user()?'Meu painel':'Entrar / Cadastrar';document.getElementById('header-account').href=user()?'#'+(admin()?'gestao':'painel'):'#login';content.innerHTML=(storageError?`<p role="alert" class="callout">${escapeHtml(storageError)}</p>`:'')+pages[page]();document.title='Simpatia257 · '+(content.querySelector('h1')?.textContent||'Início');}
function validSchedule(d){if(!['A','D'].includes(d.room)||!/^\d{4}-\d{2}-\d{2}$/.test(d.date)||!/^\d{2}:\d{2}$/.test(d.start)||!/^\d{2}:\d{2}$/.test(d.end)||d.end<=d.start)throw Error('Informe sala, data e um horário de término após o início.');}
function requireRequest(id,onlyAdmin=false){const r=db.requests.find(r=>r.id===id);if(!user()||!own(r)||(onlyAdmin&&!admin()))throw Error('Entre com a conta adequada para acessar este pedido.');return r;}
function revise(r,d){validSchedule(d);const candidate={...r,...d};if(db.requests.some(other=>other.status==='Confirmada'&&overlaps(candidate,other)))throw Error('Esse horário já tem uma reserva confirmada. Escolha outro.');Object.assign(r,{room:d.room,date:d.date,start:d.start,end:d.end,status:'Em análise',quote:null,signed:false,paid:false,proposal:null});}
function submitLocal(kind,d,id){let destination=admin()?'gestao':'painel';commit(()=>{
if(kind==='login'){const u=db.users.find(u=>u.email===d.email.trim().toLowerCase()&&u.password===d.password);if(!u)throw Error('E-mail ou senha incorretos.');db.session=u.id;destination=u.role==='admin'?'gestao':'painel';return;}
if(kind==='register'){if(!d.name.trim()||d.password.length<6||d.password!==d.confirm)throw Error('Informe seu nome e confirme a mesma senha de pelo menos 6 caracteres.');const email=d.email.trim().toLowerCase();if(db.users.some(u=>u.email===email))throw Error('Este e-mail já está cadastrado.');const u={id:uid(),name:d.name.trim(),email,password:d.password,role:'cliente'};db.users.push(u);db.session=u.id;destination='painel';return;}
if(!user())throw Error('Entre antes de continuar.');
if(kind==='profile'){const email=d.email.trim().toLowerCase();if(!d.name.trim()||db.users.some(u=>u.email===email&&u.id!==user().id))throw Error('Nome inválido ou e-mail já cadastrado.');Object.assign(user(),{name:d.name.trim(),email,phone:d.phone,organization:d.organization});return;}
if(kind==='reserve'){validSchedule(d);if(!d.title.trim()||!Number.isInteger(+d.participants)||+d.participants<1)throw Error('Informe atividade e participantes.');const r={id:uid(),userId:user().id,room:d.room,date:d.date,start:d.start,end:d.end,title:d.title.trim(),participants:+d.participants,details:d.details,status:'Em análise',signed:false,paid:false};if(conflicts(r).length){r.status='Em espera';r.message='Há outro pedido neste horário. A equipe avaliará a disponibilidade.';}db.requests.unshift(r);destination='reserva?id='+r.id;return;}
const r=requireRequest(id,['quote','propose'].includes(kind));if(!active(r))throw Error('Este pedido está encerrado.');
if(kind==='quote'){if(r.status==='Confirmada')throw Error('Reserva já confirmada.');const total=+d.total,fee=+d.fee;if(!Number.isFinite(total)||!Number.isFinite(fee)||total<=0||fee<0||fee>total)throw Error('A taxa deve ficar entre zero e o valor total.');r.quote={total,fee,notes:d.notes};r.signed=false;r.paid=false;r.status='Orçamento enviado';r.message='Novo orçamento recebido. Consulte a proposta.';destination='avaliar?id='+id;}
else if(kind==='change'){if(r.change)throw Error('Já existe uma solicitação aguardando avaliação.');if(d.kind!=='cancel')validSchedule(d);r.change={kind:d.kind,room:d.room,date:d.date,start:d.start,end:d.end,reason:d.reason};destination='reserva?id='+id;}
else if(kind==='propose'){validSchedule(d);r.proposal={room:d.room,date:d.date,start:d.start,end:d.end,reason:d.reason};r.message='A equipe propôs outra data ou horário. Confira os detalhes.';destination='avaliar?id='+id;}
});go(destination);}
function perform(kind,id){if(kind==='reset'){if(!confirm('Apagar cadastros e pedidos de teste deste site e restaurar as contas de exemplo?'))return;const fresh=seed();localStorage.setItem(STORE,JSON.stringify(fresh));db=fresh;storageError='';go('login');render();return;}if(kind==='logout'){commit(()=>db.session=null);go('login');return;}
if(['cancel','reject'].includes(kind)&&!confirm('Encerrar este pedido de teste?'))return;
commit(()=>{const adminOnly=['wait','cancel','reject','confirm','remind','approve-change','deny-change'];const r=requireRequest(id,adminOnly.includes(kind));if(!active(r))throw Error('Este pedido já foi encerrado.');
if(kind==='wait'){if(r.status==='Confirmada')throw Error('Reserva já confirmada.');r.status='Em espera';r.message='A equipe está avaliando a disponibilidade. Aguarde.';}
if(kind==='cancel'||kind==='reject'){r.status=kind==='cancel'?'Cancelada':'Recusada';r.change=null;r.proposal=null;}
if(kind==='sign'||kind==='pay'){if(!r.quote)throw Error('Aguarde um orçamento.');if(kind==='sign')r.signed=true;else r.paid=true;}
if(kind==='confirm'){if(!r.quote||!r.signed||!r.paid)throw Error('Termo e taxa devem estar concluídos.');if(r.change||r.proposal)throw Error('Resolva as solicitações de alteração antes de confirmar.');if(db.requests.some(other=>other.status==='Confirmada'&&overlaps(r,other)))throw Error('Já existe uma reserva confirmada neste horário.');r.status='Confirmada';r.message='Reserva confirmada na demonstração.';}
if(kind==='remind')r.message='Lembrete: conclua as simulações de termo e taxa para a equipe confirmar.';
if(kind==='approve-change'){if(!r.change)throw Error('Nenhuma solicitação pendente.');if(r.change.kind==='cancel'){r.status='Cancelada';r.proposal=null;}else revise(r,r.change);r.change=null;r.message='Solicitação aprovada. Alterações de agenda exigem nova avaliação e orçamento.';}
if(kind==='deny-change'){r.change=null;r.message='A alteração foi recusada. A agenda anterior foi mantida.';}
if(kind==='accept-proposal'){if(!r.proposal)throw Error('Proposta indisponível.');revise(r,r.proposal);r.change=null;r.message='Novo horário aceito. Aguardando orçamento atualizado.';}
if(kind==='deny-proposal'){r.proposal=null;r.message='Proposta de horário recusada pelo cliente.';}
});render();}
document.addEventListener('submit',event=>{const f=event.target;if(!f.dataset.form)return;event.preventDefault();try{submitLocal(f.dataset.form,Object.fromEntries(new FormData(f)),f.dataset.id);}catch(error){f.querySelector('.form-error').textContent=error.message;}});
document.addEventListener('click',event=>{const button=event.target.closest('[data-action]');if(button){try{perform(button.dataset.action,button.dataset.id);}catch(error){notify(error.message);}}else if(event.target.closest('[data-demo]'))notify('O chat é apenas ilustrativo. Nenhuma mensagem é enviada.');});
document.addEventListener('change',event=>{if(event.target.name==='kind'){const block=event.target.form.querySelector('[data-change-schedule]');block.hidden=event.target.value==='cancel';block.querySelectorAll('input,select').forEach(el=>el.disabled=block.hidden);}});
window.addEventListener('hashchange',()=>{render();content.focus();window.scrollTo(0,0)});
window.addEventListener('storage',event=>{if(event.key===STORE){location.reload();}});
render();
